### PR TITLE
Update products.js

### PR DESCRIPTION
**Pull request by vitaly-t**
not related to vulnerability, it is quite pointless creating a new database object for every request, and goes against the library's documentation.

### CODE REVIEW

**Comment by cr0hn** [comment]
Thank you very much for the PR. I'm not a profesional nodejs programmer :)

**Comment by vitaly-t** [comment]
@cr0hn 

>I'm not a professional nodejs programmer :)

You will be, it is awesome! ;)

From all the bad code that I'm seeing, it is mostly done by developers who do not allocate time to research how to do things properly :cry:

**Comment by cr0hn** [comment]
You're right. The purpose are two: 
- Use the project to teach to developers.
- Use the project to test the security tools analyzers. 

I'll document the code to be easy to learn the insecurities for developers. 

You're invited to add any new feature and/or vulnerability :)

**Comment by vitaly-t** [comment]
>You're invited to add any new feature and/or vulnerability :)

Thank you, ...cringing... :see_no_evil: I'm constantly fighting with those :punch:, can't bring myself to create them :smile:

**Pull request merged**
